### ISSUE TITLE
Course List macros should have the ability to exclude certain courses

### ISSUE THREAD

**Issue by bnehoran** [TigerAppsOrg/TigerPath#100]
for example, to represent:
All 300 level COS courses except COS 397 and COS 398 (which are independent work)

Not sure how that should be written in the list.
Maybe something like
```javascript
"course_list": [
  "COS 3** -COS 397 -COS 398: Any 300-level COS course except IW",
  "COS 4** -COS 497 -COS 498: Any 400-level COS course except IW"
]
```

With the comments (everything after the colon is ignored anyway), it would be
```javascript
"course_list": [
  "COS 3** -COS 397 -COS 398",
  "COS 4** -COS 497 -COS 498"
]
```

This doesn't look that great though, so maybe someone has a better idea for how to do this.

**Comment by bnehoran** [comment]
or maybe this looks better?
```js
"course_list": [
  "-COS 397",
  "-COS 398",
  "-COS 497",
  "-COS 498",
  "COS 3**",
  "COS 4**"
]
```

**Comment by bnehoran** [comment]
What's better? Adding it directly into the course_list as above, or putting it in a separate json field?
```JavaScript
"excluded_courses": [
  "COS 397",
  "COS 398",
  "COS 497",
  "COS 498"
],
"course_list": [
  "COS 3**",
  "COS 4**"
]
```

This might eliminate the problem of needing to read the negative items in the course_list before the positive ones, although it's not really that big a problem.

This might also have the extra advantage that it's backwards compatible. If the verifier doesn't recognize negative items, then it will still work as before. Though I don't know if backwards compatibility is even useful here.

**Comment by bnehoran** [comment]
We could also potentially decide to support more than one way of notating it, which would not be hard to do, but might be clunky and confusing.

**Comment by churichard** [comment]
I like adding it directly into the course_list. That way, you can't "forget" to exclude certain courses from counting.

**Comment by bnehoran** [comment]
I'm not sure what you mean by forget? 
Do you mean, if we add it to the JSONs but forget to add that functionality to the verifier? Not sure why that would happen by mistake. It could be that we do that because we want to make changes in smaller steps, though.

Also, how would the information then be passed up in the collapsed course lists?
Courses could be excluded from one subtree, but not from another, and so just merging them wouldn't work.
