### ISSUE TITLE
CBE doesn't appear under `Fully Supported` in the the settings dropdown

### ISSUE THREAD

**Issue by bnehoran** [TigerAppsOrg/TigerPath#109]
CBE is now fully supported, but doesn't appear as such in the dropdown on the settings page.

![image](https://user-images.githubusercontent.com/9757500/40246630-6ebd804a-5a97-11e8-81b2-96c474234474.png)

**Comment by churichard** [comment]
Solved, remember to run `python manage.py loaddata major_mappings` after you change the major_mappings json
