### ISSUE TITLE
Proposal: Use YAML instead of JSON for encoding requirement specifications

### ISSUE THREAD

**Issue by bnehoran** [TigerAppsOrg/TigerPath#173]
YAML allows for more flexibility than JSON, and might allow us to factor out requirements to make them more readable and maintainable.
https://en.wikipedia.org/wiki/YAML

In particular, YAML has references and anchors, which we could use, for example, to encode the course lists separately from the structure of the major, and then just link to those course lists from within the structure.
Then, whenever the course lists change, we don't have to search through the structure to find each of the places where the course lists appears in order to update it. This would make it easier to encode and to maintain.
YAML also allows comments and other features that would be very nice to have for maintainability.

JSON is a subset of YAML, so the existing requirement JSON files wouldn't initially need to be changed and should work as is.
New requirements can be written in a simpler way, and we can update the old ones gradually to simplify them.

Maybe there are other formats that are just as good or better. I haven't really done an extensive search, but YAML seems to have this advantage of compatibility with the existing JSONs and at the same time adding useful functionality.

**Comment by churichard** [comment]
I think that's an interesting idea. It definitely has the potential to make it easier to create and maintain the requirement specs.

I think the one downside with YAML is that it might not have the first-class support that JSON has, so it may be a little more annoying to parse through. The benefits of using it might outweigh this downside, though.

Could you try encoding an existing major in YAML to see what it would look like (e.g. COS BSE)?

**Comment by bnehoran** [comment]
I've switched to a YAML parser, and everything works without a problem with no other changes needed.

**Comment by bnehoran** [comment]
This allows writing neater requirements.
For example, this is what the COS-BSE major looks like as a (simplified) YAML:
https://github.com/TigerPathApp/tigerpath/blob/verifier-updates/tigerpath/majors_and_certificates/majors/COS-BSE_2018.yaml

Compare to the original JSON (/unsimplified YAML):
https://github.com/TigerPathApp/tigerpath/blob/verifier-updates/tigerpath/majors_and_certificates/majors/COS-BSE_2018.json

Of course, we don't need to convert any of the existing JSONs if we don't want to, but any new requirements can made cleaner.
