### ISSUE TITLE
Requirements tree doesn't load on first visit to the app

### ISSUE THREAD

**Issue by bnehoran** [TigerAppsOrg/TigerPath#177]
On `dev` branch

When I first logged in to the app, there was no requirements tree, and the right pane was blank.
It only appeared once I started adding courses.

I'm not sure if this happens for all users, so this should be verified.

If it doesn't load, it looks pretty empty, and so that's not a good look for first time users.

**Comment by churichard** [comment]
Not reproducible, so closing this.
