### ISSUE TITLE
Make gray the color for courses that fit in both semesters

### ISSUE THREAD

**Issue by bnehoran** [TigerAppsOrg/TigerPath#179]
Maybe courses that can fit in either semester should be gray.
It seems more clear visually that they can fit in either semester this way.

This is what it currently looks like:
![image](https://user-images.githubusercontent.com/9757500/50809457-86c47e80-12d1-11e9-93a3-d0e6e662dcfb.png)
Orange courses look like they just belong to a different, third category, which is not the impression we want.

---

And here's an idea of what it would look like:
![image](https://user-images.githubusercontent.com/9757500/50809418-4ebd3b80-12d1-11e9-99f4-de38565db670.png)
I think you can see the dichotomy of colors much better.

**Comment by churichard** [comment]
I agree that you can see which courses match which semesters better in that screenshot, but I'm not sure if grey would be the best color to use. Grey kind of signifies that the course is disabled or inactive in some way, which is not the impression we want to give.

I think having a color that's a mix of the current purple and blue being used would be better. I picked out a middle color using this website: https://meyerweb.com/eric/tools/color-blend/#AD79D4:3AAED4:10:hex and adjusted it a little bit to end up with the following:

<img width="1203" alt="screen shot 2019-01-12 at 9 29 57 pm" src="https://user-images.githubusercontent.com/4218237/51081943-4e49e980-16b1-11e9-9e94-edb65086c413.png">

For reference, the background color is #b2c0e6 and the text color is #1d2848. I think this looks better than the orange currently being used, as well as the proposed grey.

**Comment by bnehoran** [comment]
Yeah, I guess it might make it seem disabled, so I don't know.
The middle color you choose looks to me (personally) much more like the blue than the purple. I don't know if everyone sees it the same way, but I would probably be confused by that.

Maybe what we really need is like a sort of decontrasted striped purple/blue background. Something that clearly indicates "both colors".

And I guess we just really need to add the warning when they add a course in the wrong semester.
