### ISSUE TITLE
AAS 201 appears twice

### ISSUE THREAD

**Issue by bnehoran** [TigerAppsOrg/TigerPath#330]
AAS 201 appears twice in search. Is that expected? Why is this?
![image](https://user-images.githubusercontent.com/9757500/86856782-0976f700-c08b-11ea-9d89-26fcfed252d1.png)

**Comment by pranavavva** [comment]
It seems that the AAS department reused the AAS201 number for a different course starting Fall 2019. There's possibly two records in the database for AAS201, each with a different course name.

**Comment by bnehoran** [comment]
Yeah, I guess that makes sense. If it's actually two entirely different courses, then I guess this isn't an error.
I'll close this issue, then.

Thanks for looking into this!

**Comment by pranavavva** [comment]
Might be an issue if one version of "AAS201" is no longer offered. I poked around the database and found that there are in fact two records where `dept` is AAS and `number` is 201.

![image](https://user-images.githubusercontent.com/23485492/88603326-8ec64980-d042-11ea-8fc3-688fd5fc15fc.png)

We'll have to wait and see if AAS201 is offered again in the spring before making any changes though.
