### ISSUE TITLE
Taking Sanskrit 101-107 doesn't satisfy a BSE Foregin Language distribution.

### ISSUE THREAD

**Issue by pranavavva** [TigerAppsOrg/TigerPath#357]
**Describe the bug**
After adding SAN 101 to Fall 1, SAN 102 to Spring 1, SAN 105 to Fall 2, and SAN 107 to Spring 2, the Foreign Language distribution still has a 0, even though SAN 107 *should* fulfill it.

**To Reproduce**
1. Go to TigerPath.
2. Choose a BSE major in Settings.
3. Add SAN 101, SAN 102, SAN 105, SAN 107 to the schedule as described previously.
4. You should see that Foreign Language is still yellow and has a 0.

**Expected behavior**
Foreign Language should have a 1 and turn green.

**Screenshots**
![setup](https://user-images.githubusercontent.com/23485492/88204373-2974f180-cc19-11ea-98f1-ea0844e18576.png)
![bug](https://user-images.githubusercontent.com/23485492/88204437-401b4880-cc19-11ea-8826-bb7d26e59e64.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1909 Build 18363.959
 - Browser Firefox 78.0.2
 - Major COS (BSE)

**Additional context**
None.

**Comment by bnehoran** [comment]
Thanks for pointing this out, @pranavavva! 
You're right, that must have been an oversight.

Let me try to push a fix for it.

**Comment by bnehoran** [comment]
Hi @pranavavva. I've now opened pull request #358 which should hopefully fix this once it's merged in.

**Comment by bnehoran** [comment]
Alright, it should hopefully be fixed now. Try refreshing the page, and maybe removing and then re-adding the courses, and see if it now appears under the language requirement.
If not, then let me know!

Thanks again @pranavavva for pointing this out!

**Comment by pranavavva** [comment]
Awesome! The foreign language requirement is coming up as green as expected. But now upper-level SAN courses (SAN 300/303) is showing up twice. I can choose to settle them under the LA or foreign language distributions, but when I settle them under LA, it is coming up double in the Seven Total Courses.

I think the logic here is probably similar to how departmentals (at least for COS BSE) can be settled under either a specific category (for example Systems) or General. I believe the bug is coming from how total courses are counted.
See screenshot: 
![Annotation 2020-07-22 165331](https://user-images.githubusercontent.com/23485492/88227669-ebd59000-cc3b-11ea-9c63-6f973fc7970b.png)

**Comment by pranavavva** [comment]
@bnehoran sorry for the ping, not sure if you saw this

**Comment by bnehoran** [comment]
@pranavavva Thanks for the update! I'm glad that first problem seems to have been solved.

As for courses counting twice under the "Seven Total Courses", I think I know why this is happening. It's a separate problem with how that requirement is currently evaluated.
What it's doing at the moment is adding up the courses that could satisfy each of the "Humanities and Social Sciences" categories, and then summing up those subtotal, which fails when a course like this falls into multiple categories (`SAN 300 / TRA 300` explicitly satisfies `LA`, but it also completes the language requirement by virtue of having `SAN 107` as a prerequisite).

I expanded this out into a new issue at https://github.com/TigerPathApp/tigerpath/issues/359 so that it's easier to keep track, and since it's a different problem than the one from this issue.
Let me see if I can find a good way to fix it. 

I see that you have programming experience, by the way, so if you would like to help out with this, just let me know and I can try to familiarize you with the relevant parts of the code!

**Comment by pranavavva** [comment]
I would love to help! I am learning React/Node, but I'm not too familiar with Python and Django, but I'm totally willing to learn!

**Comment by bnehoran** [comment]
Awesome! I would be happy to help you out!

The changes to fix this issue (with some courses counting twice for the "Seven Total Courses") will probably involve mainly editing python and json/yaml code, as it's mostly dealing with how the BSE requirements are encoded into a file as well as how they are interpreted.
If you are interested, you might want to take a look at the documentation [here](https://github.com/TigerPathApp/tigerpath/tree/master/tigerpath/majors_and_certificates), which explains how the requirements files are structured, and what the different parts mean.
The BSE requirements, specifically, are located in [this file](https://github.com/TigerPathApp/tigerpath/blob/master/tigerpath/majors_and_certificates/degrees/BSE_2018.json).
The interpretation of requirement files (that is, the actual evaluation of the logic encoded in them, as well as the decisions of what gets displayed in the requirements tree panel on the right of the app) occurs in [verifier.py](https://github.com/TigerPathApp/tigerpath/blob/master/tigerpath/majors_and_certificates/scripts/verifier.py), but the logic here is a bit complex so I wouldn't get too buried in it.
We should probably continue the discussion about this on the page I opened for the issue, https://github.com/TigerPathApp/tigerpath/issues/359, just to keep things organized. But yeah, I would be happy to help you out!

If you'd like to do something specifically with React or Node, you might consider taking a look at some of the other [open issues](https://github.com/TigerPathApp/tigerpath/issues) we have, especially some further down the list which deal with UI and user data related features and updates. If you want me to help point you to some that would be relatively easier for a first-time contribution, let me know!
