### ISSUE TITLE
Some language courses are counting double towards total BSE humanities count

### ISSUE THREAD

**Issue by bnehoran** [TigerAppsOrg/TigerPath#359]
Expanded from https://github.com/TigerPathApp/tigerpath/issues/357#issuecomment-662691932. cc: @pranavavva 

It seems that whenever a language course also has another distribution requirement designation (for example `SAN 300 / TRA 300` counts as `LA`, while also implicitly completing the language requirement by virtue of requiring `SAN 107` as a prereq), it's being counted as double in the "Seven Total Courses" count for the BSE Humanities and Social Sciences requirement.

This is because the [current structure](https://github.com/TigerPathApp/tigerpath/blob/975990fb2ca97f5d949774d3537bf271c2c6f5a2/tigerpath/majors_and_certificates/degrees/BSE_2018.json#L306-L362) counts the courses under each subcategory and then adds them up, which is only correct as long as no course falls under more than one category, which is why it falls apart here.

Two possible fixes come to mind:
* The best way would probably be to just count them all together in one subrequirement. This would require a slight update to the requirements file format.
* A simpler solution to implement, but which wouldn't be quite as clean, would be to just exclude language courses from counting in the other subcategories of the "Seven Total Courses" requirement.

The second one would probably be quite messy and wouldn't really solve the underlying issue, so it would probably be best to go with the first.

**Comment by pranavavva** [comment]
I'm looking at how to set up a dev environment locally... do I need to have a postgres database running locally? And I'm confused about the TIGERBOOK env vars in [.env-example](https://github.com/TigerPathApp/tigerpath/blob/master/.env-example). The tigerbook API endpoint seems to down, unless I'm not using it correctly?

**Comment by bnehoran** [comment]
Hi @pranavavva. I sent you an email with some more details.
It seems that the tigerbook API is just unavailable at the moment while USG is looking for maintainers, but that shouldn't really be a problem since it's not crucial to TigerPath.
