### ISSUE TITLE
Non-romance languages from 105+ should fulfill BSE Foreign Language dist req.

### ISSUE THREAD

**Issue by pranavavva** [TigerAppsOrg/TigerPath#365]
According to the [Engineering website](https://engineering.princeton.edu/undergraduate-studies/first-year-advising/degree-requirements), Romance languages from the 107-level and up count to the Foreign Language dist req. However, **non-Romance** languages from the **105**-level and up count to the Foreign Language dist req.

I don't know exactly what counts as a "Romance language." It's probably published on one of Princeton's websites somewhere, or I may just have to contact someone at Princeton to get a list of the Romance languages.

**Comment by pranavavva** [comment]
The only languages that could be called "Romance languages" that Princeton offers are Portuguese, Italian, Spanish, and French. One way of approaching this would be to create a "pseudo-department" like "LANG" for just POR, ITA, SPA, and FRE. We could probably call this pseudo-department "RLANG" for "Romance language". We could then create another pseudo-department "NRLANG" for "Non-Romance Language". Then within the `BSE_2018.json` file we could add a "NRLANG 105" where we need to.

@bnehoran do you know where LANG is defined as a "department" in the code? I tried looking around but couldn't find it.

**Comment by bnehoran** [comment]
Interesting. I wonder if it might be a new policy. It's the first time I've seen it.
That page is also the only place where I can find it mentioned. Every other location, it simply says "Language at the 107/108 level".
Either way, I agree that we'd probably want to clarify exactly what the exact policy is.

In terms of implementation, I think it's a bit too specific a restriction to create a whole new designation for it, but you can implement it using the existing tools.
For example,
```yaml
"course_list": [
  "LANG 105"
],
"excluded_course_list": [
  "FRE 105",
  "ITA 105",
  "POR 105",
  "SPA 105"
]
```
should do the trick for "105 level of a non-romance language", if those are indeed the only four that count as romance languages.

**Comment by bnehoran** [comment]
By the way, I also wonder if Latin counts as a "Romance language" under the policy. After all, it is the mother of all romance languages, though it's not a currently spoken one.

**Comment by pranavavva** [comment]
Apparently Latin is not considered a Romance language. Latin (spec. Vulgar Latin) is the mother of Romance languages, but isn't one itself.
