### ISSUE TITLE
ISC 231-234 doesn't satisfy COS 126 prereq for COS AB & BSE major but does satisfy BSE computing requirement.

### ISSUE THREAD

**Issue by pranavavva** [TigerAppsOrg/TigerPath#382]
**Describe the bug**
Add ISC 231, 232, 233, 234 to your schedule. It doesn't satisfy the COS BSE COS 126 pre-requirement but *does* satisfy the BSE computing pre-req (the latter is the correct behavior).

**Screenshots**
Schedule setup:
![image](https://user-images.githubusercontent.com/23485492/89112320-0d4e2d00-d42f-11ea-8e4d-33ac84c36118.png)

COS BSE pre-req (incorrect behavior):
![image](https://user-images.githubusercontent.com/23485492/89112323-16d79500-d42f-11ea-982e-98cb04c4879c.png)

BSE computing req (expected behavior):
![image](https://user-images.githubusercontent.com/23485492/89112326-1e973980-d42f-11ea-9ed8-4e1a726d52b4.png)

**Possible solution**
This can easily be solved by creating a "hidden sub-req" in COS-BSE.json following a similar structure to how the ISC sequence satisfies [physcis](https://github.com/TigerPathApp/tigerpath/blob/master/tigerpath/majors_and_certificates/degrees/BSE.json#L147-L155), [chemistry](https://github.com/TigerPathApp/tigerpath/blob/master/tigerpath/majors_and_certificates/degrees/BSE.json#L182-L190), and [computer science](https://github.com/TigerPathApp/tigerpath/blob/master/tigerpath/majors_and_certificates/degrees/BSE.json#L216-L224) in BSE.json. I will be pushing a fix branch shortly.

**Comment by pranavavva** [comment]
I also noticed that ISC 231-234 has the same problem for the COS AB major pre-reqs. I will include a fix for this in my PR.

**Comment by bnehoran** [comment]
@pranavavva Thanks for finding and fixing this!

**Comment by bnehoran** [comment]
By the way, are any other majors where the ISC curriculum satisfies the prereqs and for which we don't yet support that? I can see that our MOL encoding supports this explicitly, but I'm now wondering if there are any other majors that we missed.
