### ISSUE TITLE
Fix Logout Button

### ISSUE THREAD

**Issue by bnehoran** [TigerAppsOrg/TigerPath#46]
Clicking on the username should not turn it into a logout button, but instead there should be an arrow next to it that pops out a menu with something that is/functions as a logout button.

After logging out, the user should be redirected to the the tigerpath homepage (where they were before they logged in).

**Comment by churichard** [comment]
#83 and #88 fix the first issue.

**Comment by churichard** [comment]
#98 fixes the second issue.
