### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by churichard** [TigerAppsOrg/TigerPath#49]
- Loading circles when searching courses
- Should tell you "X Search Results" when you search for something (like Recal/Princeton Courses). This is mostly to indicate something to the user when there aren't any results
- Requirement header for the top level of major/degree should turn green when you've satisfied all requirements for major/degree
- Show requirements pane on first login by a user, i.e. when the user_schedule is NULL in the database

**Comment by danielleung27** [comment]
Showing requirements pane on null schedule fixed in #47 (really quick fix so I just fixed it in my current pr)

**Comment by danielleung27** [comment]
#53 shows search result count and main req turns green when satisfied.

**Comment by bnehoran** [comment]
It seems that all the mentioned items have been addressed, so I'm closing the issue.
